name: Frontend CD
on:
  push:
    branches: [master]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '15'
      - uses: warchant/setup-sonar-scanner@v3
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: sonar-scanner
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
  deploy:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: dist/elective-management-system-site
      - name: Upload dist zip
        uses: leandro-hermes/action-upload-file@v1.1.0
        id: uploadFile
        with:
          host: "http://amrita-elective.tk:4000/new-frontend-build"
          path: "/"
          filePath: "result.zip"
          data: ${{ secrets.EC2_LOGIN }}
      - run: echo ${{ steps.uploadFile.outputs.response }}
      - if: ${{ steps.uploadFile.outputs.response == '"OK"' }}
        run: exit 0
      - if: ${{ steps.uploadFile.outputs.response != '"OK"' }}
        run: exit 1
